# Generated by Django 3.1.3 on 2021-10-26 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20211025_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_pics')),
                ('comments', models.CharField(max_length=255)),
                ('post_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='user_like', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='main.Tags')),
            ],
        ),
    ]
