# Generated by Django 3.1.3 on 2021-10-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='details',
            new_name='post_content',
        ),
    ]
