# Generated by Django 3.1.3 on 2021-10-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211026_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_at',
            new_name='posted_at',
        ),
    ]
