# Generated by Django 3.1.3 on 2021-11-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211102_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='post_image',
        ),
    ]
