# Generated by Django 3.1.3 on 2021-11-08 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20211102_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='shares',
            field=models.ManyToManyField(related_name='user_share', to=settings.AUTH_USER_MODEL),
        ),
    ]
