# Generated by Django 3.1.3 on 2021-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
