# Generated by Django 3.1.3 on 2021-11-09 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211109_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_cont',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post_to_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.posts'),
            preserve_default=False,
        ),
    ]
