# Generated by Django 3.1.3 on 2021-11-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_comment_post_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_to_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.posts'),
            preserve_default=False,
        ),
    ]
