# Generated by Django 3.1.3 on 2021-11-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_comment_post_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_to_comment',
        ),
    ]
