# Generated by Django 3.1.3 on 2021-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_comment_post_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='shares',
        ),
        migrations.AddField(
            model_name='posts',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
