# Generated by Django 3.1.3 on 2022-01-03 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='thumbs',
            field=models.ManyToManyField(blank=True, default=None, related_name='thumbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='thumbsdown',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='questions',
            name='thumbsup',
            field=models.IntegerField(default='0'),
        ),
    ]
