# Generated by Django 3.1.3 on 2022-01-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='thumbs',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='thumbsdown',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='thumbsup',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
