# Generated by Django 3.1.3 on 2022-01-12 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0032_auto_20220112_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='userDownVotes',
            field=models.ManyToManyField(blank=True, related_name='threadDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='userUpVotes',
            field=models.ManyToManyField(blank=True, related_name='threadUpVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
