# Generated by Django 3.1.3 on 2022-01-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220112_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='userDownVotes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='userUpVotes',
        ),
    ]
