# Generated by Django 3.1.3 on 2021-11-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_posts_author'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackoverflowuser',
            name='post_posted',
            field=models.ManyToManyField(blank=True, to='main.Posts'),
        ),
    ]
