# Generated by Django 3.1.3 on 2021-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_stackoverflowuser_post_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackoverflowuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_pics'),
        ),
    ]
