# Generated by Django 3.1.3 on 2021-11-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_stackoverflowuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflowuser',
            name='image',
        ),
    ]
